name: To production! 
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |

          cd /var/www/ushauri_dashboard
          git pull origin master
          # optimizations
          php artisan config:cache
          php artisan event:cache
          php artisan view:cache
          php artisan route:cache
