name: deploy to test instance
on:
  push:
    branches: [ encryption ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/github-workflows/mhealth-apps/encryption
          sudo rm -rf ushauri_dashboard
          sudo mkdir ushauri_dashboard
          sudo chown -R cicd2:cicd2 ushauri_dashboard
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/encryption/ushauri_dashboard/      
          cd ushauri_dashboard
          git clone -b main https://github.com/palladiumkenya/ushauri_dashboard.git .
          git status
          cp /apps/configs/ushauri-dashboard-encryption/.env /apps/github-workflows/mhealth-apps/encryption/ushauri_dashboard/
          cp /apps/configs/ushauri-dashboard-encryption/docker-compose.yml /apps/github-workflows/mhealth-apps/encryption/ushauri_dashboard/
          cp /apps/configs/ushauri-dashboard-encryption/nginx.dockerfile /apps/github-workflows/mhealth-apps/encryption/ushauri_dashboard/
          cp /apps/configs/ushauri-dashboard-encryption/php.dockerfile /apps/github-workflows/mhealth-apps/encryption/ushauri_dashboard/
          cp -r /apps/configs/ushauri-dashboard-encryption/nginx /apps/github-workflows/mhealth-apps/encryption/ushauri_dashboard/
          docker-compose down
          docker-compose rm -fv
          docker-compose --env-file .env up -d --build
          # execute normal laravel commands
          docker-compose exec -T php_encryption composer install --ignore-platform-reqs --no-dev
          docker-compose exec -T php_encryption php artisan config:cache
          docker-compose exec -T php_encryption php artisan view:cache
          docker-compose exec -T php_encryption chmod -R 777 storage/
          docker-compose exec -T php_encryption php artisan config:cache
          docker-compose exec -T php_encryption php artisan config:clear
          echo "done!"
